### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by fzyzcjy** [gskinnerTeam/flutter-defer-pointer#5]
Hi thanks for the lib! I wonder whether this is ready for production?

**Comment by esDotDev** [comment]
Yep, if you find any issues please post em here.

**Comment by fzyzcjy** [comment]
Thanks! I saw several issues in the issue tracker without reply, so I was worried this lib was deprecated...

**Comment by esDotDev** [comment]
No definitely not, I'll take a look at those issue!

**Comment by fzyzcjy** [comment]
Get it :)
